// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxeipgzcepteigyziwxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4ZWlwZ3pjZXB0ZWlneXppd3hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjE1NTcsImV4cCI6MjA3MDU5NzU1N30.t4WWsnB1DNICSvgBM9FN8ooAVmeLWB-ajK3dFv66MZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});